{% set version = "1.1.9" %}

package:
  name: jupyterlab_widgets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/jupyterlab_widgets/jupyterlab_widgets-{{ version }}.tar.gz
  sha256: 5620c797dcdaa64f98a3e35605753c5902f23a8e7d754bc82b851c71df625ca5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - jupyter-packaging

  run:
    - python >=3.7

  run_constrained:
    - jupyterlab >=3,<5

test:
  imports:
    - jupyterlab_widgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/jupyter-widgets/ipywidgets
  summary: JupyterLab extension providing HTML widgets
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jasongrout
    - SylvainCorlay
    - martinRenou
    - jtpio
    - bollwyvl
